// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_COMP_COIN_H
#define _UI_COMP_COIN_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT coin
#define UI_COMP_COIN_COIN 0
#define UI_COMP_COIN_NAME 1
#define UI_COMP_COIN_DESCRIPTION_PRICE 2
#define UI_COMP_COIN_COUNT 3
#define UI_COMP_COIN_ITEMS_VALUE 4
#define UI_COMP_COIN_IMAGE 5
#define _UI_COMP_COIN_NUM 6
lv_obj_t *ui_coin_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
